### ISSUE TITLE
Setup initial frontend environment

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#10]
## Description
Prepare initial frontend environment so team can start development.

## Tasks

- [x] Start a React project
- [x] Integrate Redux
- [x] Integrate react-dom
- [x] Integrate material-ui
- [x] Integrate react-scripts
- [x] Integrate react-router
- [x] Integrate eslint
- [x] Integrate prettier
- [x] Prepare a docker container with react environment
- [x] Update gitignore
