### ISSUE TITLE
Criar Roadmap dos papéis

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#107]
## Descrição

Deve ser criado um diagrama de roadmap ilustrando o que cada gerente pretende realizar de tarefa do seu papel até a R1.

## Tarefas

- [x] Criar template
- [x] Adicionar tarefas de Arquitetura
- [x] Adicionar tarefas de DevOps
- [x] Adicionar tarefas de Engenheiro de produto
- [x] Adicionar tarefas de ScrumMaster
- [x] Ao final o diagrama deve estar disponível no github pages do projeto com as tarefas de todos os papéis elicitadas

**Comment by icaropires** [comment]
O template foi criado e pode ser visualizado [aqui](https://docs.google.com/spreadsheets/d/1Wk9N9ItT7frXfL9IvOn7ZVAOPFcqtAwj6WKRGJUEUuU/edit?usp=sharing) mas só pode ser alterado por membros da aquipe.

**Comment by Bumbleblo** [comment]
Esse épico está replicado com o épico #88

**Comment by icaropires** [comment]
Realmente, podemos manter somente esse que está mais completo?

**Comment by joaorobson** [comment]
Posso fechar esse épico? O @Bumbleblo não adicionou no template, mas em uma aba separada. Tudo ok por você, @icaropires ?

**Comment by icaropires** [comment]
Acho que você @joaorobson e o @ViniciusBernardo podem decidir isso.

**Comment by Bumbleblo** [comment]
Como os roadmaps iniciais foram criados estou fechando esse épico. Atualizações e melhorias podem ser adicionados posteriormente referente a épicos da release 2.
