### ISSUE TITLE
Setup initial CI

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#13]
## Description

Setup initial CI to avoid messy code being sent to devel branch.

## Tasks

- [x] Choose a CI platform
- [x] Integrate the CI platform
- [x] Run tests
- [x] Run linter
- [x] Make build fail if any of past steps fail

**Comment by Bumbleblo** [comment]
That CI pipeline have code style step ?

**Comment by icaropires** [comment]
@Bumbleblo Yes, it's included in linter step.

**Comment by icaropires** [comment]
I'd like to use gitlab Ci for this project, but according to gitlab in [this page](https://about.gitlab.com/solutions/github/), it's not totally free:

![image](https://user-images.githubusercontent.com/18473249/54880788-c9551c00-4e27-11e9-9287-814b4fb9448e.png)

**Comment by icaropires** [comment]
I don't want to prepare physical machines to run CI because we'd need a physical machine, public IP, etc. So I won't use Jenkins.

**Comment by icaropires** [comment]
I'll use Travis CI which offers the infrastructure, support for the languages we'll use and docker. Besides, it's free for open source projects with no expiration time.

**Comment by icaropires** [comment]
Maybe we'll need to test for Windows, which is in early stage for Travis. If we need to run the code of this repository on Windows, and Travis environment don't be enough, I can change the CI environment. But for now Travis CI will do.

**Comment by icaropires** [comment]
Issues and Pull requests will now be in english. See #4.

**Comment by icaropires** [comment]
Uma opção para checagem de estilo poderia ser o [PrettierCI](https://www.prettierci.com/) mas não será realmente útil para o nosso projeto, uma vez que toda a formatação é feita por git hooks no ambiente de todos usuários que tenham executado chamado o entrypoint do docker pelo menos uma vez (ver solução da issue #18 )

Além disso o script de checagem pode ser facilmente chamado na integração contínua original.
