### ISSUE TITLE
Initial meeting with developer team and git training - Meeting 1

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#16]
## Description

Initial meeting with developer team (students from Method of Software Development) and initial git training.

### Objectives

* Know members
* To present the discipline
* To present initial idea of Project
* Initial practice of technologies

#### 1 - To present members (Max. 5 min each  = 45 min)
* Name
* Semester
* Where do you live?
* Have a car?
* Preferred programming language
* Whats your job? And the previous?
* Expectations

#### 2 - Talk about the discipline (Max. 40 min)
* Influence on hourly grid (5 min)
* Influence on course (5 min)
* Feedback members grid hours and subjects (10 min)
* Schedule daily (suggestion of 12:10 every day) (10 min)
* Weekly meeting (suggestion of Saturday 14h) (10 min)

#### 3 - Project (Max. 35 min)
* Context of the project (15 min)
* Current situation of project acquisition (5 min)
* Idea of initial architecture (10 min)

#### 4 - Technologies (Max. 95 min)
1. Basic concepts about bash
* mkdir
* echo
* touch
* cp
* mv
* rm

**-------------- Hint time (@icaropires ) ---------------**

2. Basic Git (15 min)
* Repository
* Fork
* Branch
* Commit
* Pull Request
* Issue

3. Perform training of basic Git (25 min)
* Create a repository
* Create a issue to each developer with tasks and label
* Download and setup Git on developers computers
* Each developer create a fork
* Each developer auto assign a issue
* Each developer create a commit with title and message
* Each developer push to respective fork repository 
* Fix conflicts with all the team helping

## Tasks
- [x] Each developer must have a fork of the main repository
- [x] Each developer must solve its issue and only it
- [x] Each developer must push to its fork and open a pull request
- [x] Ask developers to add reference to corresponding issues on pull requests
- [x] Merges will be accepted according with issue id
- [x] Initial code of repository and issues must force developers to solve conflicts

## Additional Information
**developers:** @thiagotmb, @medeiroslucas, @VictorLeviPeixoto, @tmcstiago, @GabrielTiveron 
**managers:** @icaropires, @Bumbleblo, @ViniciusBernardo, @joaorobson

**Comment by icaropires** [comment]
The meeting happened on 12/03 and all developers and managers were present. The repository used on training can be found [here](https://github.com/icaropires/eps-mds-labs) along with all information it carries.
