### ISSUE TITLE
Setup frontend linter and stylesheet tools

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#18]
## Description

Setup linter and stylesheet tools for checking contributors code, once it's done it can be integrated into CI

## Tasks

- [x] Choose linter tool
- [x] Setup linter tool for React
- [x] Choose stylesheet tools
- [x] Make stylesheet tool don't disagree with linter tool
- [x] Add script for running them on `package.json`
- [x] Add script for auto fixing small mistakes
- [x] If possible, make them be called before commit or push
- [x] Make them be called independent from developer environment (dockerize)

**Comment by icaropires** [comment]
Will be used eslint for linter tool and prettier as stylesheet tools as they seem to be widely used by the community working with React.

**Comment by icaropires** [comment]
Issues and Pull requests will now be in english. See #4.
