### ISSUE TITLE
Criar recuperação de dados locais

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#191]
## Descrição

A parte local da aplicação deve coletar os dados do dispositivo físico e enviar para o frontend de forma que ele os consiga exibir em real time.

## Tarefas

- [x] Coletar dados via serial
- [x] Os dados coletados devem ser gravados num arquivo de log
- [x] Criar forma alternativa do usuário executar a aplicação (sem ser no terminal)
- [x] Criar forma de selecionar porta via GUI
- [x] Criar forma de exibir o status atual da aplicação para o usuário via GUI
- [x] Todos requisitos devem funcionar no Windows

## Informação adicional
