### ISSUE TITLE
Documentação inicial do projeto

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.1-unbrake#21]
## Description

Esse épico tem o objetivo de definir a documentação inicial para a release 1

## Tasks

- [x] Criar documento de riscos
- [x] Criar template para pull request
- [x] Documento de arquitetura
- [x] EAP
- [x] TAP
- [x] Guia de contribuição
- [x] Politicas de branch 
- [x] Politicas para criação de issues

**Comment by Bumbleblo** [comment]
A politica de branch se encontra junto com a contribuição na issue #6

**Comment by Bumbleblo** [comment]
Não adicionem nenhuma issue além das que estão neste épico, o objetivo é elaborar o minimo de documentação do projeto e iniciar as documentações mais complexas. Caso precise de outro épico de documentação crie para sua frente.

**Comment by Bumbleblo** [comment]
Terminamos esse épico com alguns documentos iniciais prontos, agora teremos alguns outros para evoluir o que já foi feito.
