### ISSUE TITLE
Implementar comunicação com o módulo local

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#217]
## Descrição

Com a conclusão desse módulo é esperado que tanto API quanto Frontend já sejam capazes de enviar e receber dados do módulo local para todas as funcionalidades existentes da aplicação.

## Tarefas

- [x] Decidir método de comunicação (testar viabilidade do MQTT)
- [x] Subir Broker ou novo Servidor, se necessário, em ambiente de produção/homologação
- [x] Encontrar clientes MQTT para todos os módulos
- [x] Fazer o Frontend receber dados contínuos a serem plotados nos gráficos realtime
- [x] Fazer o módulo local receber comandos de realização de um ensaio
