### ISSUE TITLE
Criar formulário para configurações do ensaio

### ISSUE THREAD

**Issue by joaorobson** [fga-eps-mds/2019.1-unbrake#40]
## Descrição

Esta issue é referente ao desenvolvimento do restante do formulário para configurações gerais do simulador. A issue para criar a parte inicial do form é a #9.

## Tarefas

- [x] Utilizar [redux-form-material-ui](https://github.com/erikras/redux-form-material-ui/tree/5.0) para criar os campos editáveis.
- [ ] Alimentar os campos editáveis com as informações contidas no arquivo que pode ser inserido usando os campos criados na issue #9.
- [x] Utilizar Material-UI para criar o restante dos componentes.

## Informação adicional

Após ler o arquivo que possui a extensão ".ini", as informações devem ser passadas aos seus respectivos campos. Para realizar isso, deve-se utilizar uma biblioteca que converta o que há no arquivo para um objeto JS. A biblioteca sugerida é a [ini](https://www.npmjs.com/package/ini).

Abaixo, página correspondente no software utilizado atualmente:
![configuracao](https://user-images.githubusercontent.com/26315903/55295080-ae624900-53df-11e9-9b82-76d006b8820c.png)

**Comment by GabrielTiveron** [comment]
A tela de configuração com sua respectiva rota na issue #7 não seria uma dependência também?

**Comment by tmcstiago** [comment]
Sim @GabrielTiveron. Por isso é a ideia que eu entregue logo esta Issue.
