### ISSUE TITLE
Configurar ambiente de desenvolvimento do Frontend

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#44]
## Descrição

Preparar todo o ambiente de desenvolvimento do frontend com todas validações necessárias.

## Tarefas

- [x] Iniciar projeto
- [x] Criar docker de desenvolvimento
- [x] Preparar ferramentas linters e formatadoras
- [x] Executar ferramentas linters e formatadoras no ambiente do container
- [x] Criar scripts para a execução local por parte dos desenvolvedores das ferramentas formatadoras
- [x] Executar os scripts através de git hooks
- [x] Criar método de compartilhamento de git hooks com os desenvolvedores
- [x] Configurar integração contínua coerente com os scripts de checagem local
- [x] Notificar time sobre resultados das builds da integração contínua via Slack

## Informação adicional
As informações serão providas nas issues
