### ISSUE TITLE
Configurar ambiente de desenvolvimento do Backend

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#52]
## Descrição

Preparar todo o ambiente de desenvolvimento do backend com todas validações necessárias.

## Tarefas

- [x] Iniciar projeto
- [x] Criar docker de desenvolvimento
- [x] Preparar ferramentas linters e formatadoras
- [x] Executar ferramentas linters e formatadoras no ambiente do container
- [x] Criar scripts para a execução local por parte dos desenvolvedores das ferramentas formatadoras
- [x] Executar os scripts através de git hooks
- [x] Integrar ao método de compartilhamento de git hooks com os desenvolvedores já disponível
- [x] Adicionar à Integração Contínua as checagens do backend, coerente com os scripts de checagem local

## Informação adicional
As informações serão providas nas issues

**Comment by Bumbleblo** [comment]
@icaropires por favor assine na tarefa conforme o nosso [guida de contribuição](https://github.com/fga-eps-mds/2019.1-unbrake/blob/devel/CONTRIBUTING.md)
