### ISSUE TITLE
Create Sidebar Menu

### ISSUE THREAD

**Issue by ViniciusBernardo** [fga-eps-mds/2019.1-unbrake#7]
## Description

Implement the main Sidebar menu of the application creating the base architecture for react-dom's router selection. That base architecture must have the four initial modules (configuration, calibration, test and analysis).

## Tasks

- [x] Create link buttons for each of the four modules 
- [x] Create the routes for each of the four modules
- [x] Link each button of the first task with its respective route

### Evaluation Criteria
* Create sidebar and router selector in decoupled components
* Use the material-ui components

**Comment by VictorLeviPeixoto** [comment]
Existe algum template para ser seguido na construção da sidebar?

**Comment by ViniciusBernardo** [comment]
Yes. You can use the dashboard example at the material ui documentation. Here is the link https://material-ui.com/getting-started/page-layout-examples/dashboard/

**Comment by VictorLeviPeixoto** [comment]
Can i use react-sidenav?

**Comment by joaorobson** [comment]
Como um substituto do Menu do Material-UI?
