### ISSUE TITLE
Criar Roadmap de Devops

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#71]
## Descrição

Criar Roadmap de devops, detalhando o que pretende-se alcançar e quando (Pelo menos até a R1).

## Tarefas

- [x] Encontrar template de roadmap adequado, visto que o time ainda não possui um
- [x] Compartilhar o template com o time
- [x] Planejar o que fazer até a R1
- [x] Colocar no github pages com a parte de DevOps preenchida

**Comment by RochaCarla** [comment]
quais sao os criterios de aceitação?!!!

**Comment by icaropires** [comment]
@RochaCarla, essa issue ainda será evoluída quando eu souber melhor o que vou fazer.

Mas estamos mapeando os critérios de aceitação também como tasks. O revisor do PR avaliará se todas as tasks realmente foram cumpridas. Tem problema fazer dessa forma?

**Comment by icaropires** [comment]
Adicionei o template do diagrama de roadmap e a parte das tarefas de devops até a R1. Ele pode ser acessado aqui: [diagrama](https://fga-eps-mds.github.io/2019.1-unbrake/roadmaps/roadmap-papeis/).

**Comment by icaropires** [comment]
Se tiver tudo ok, pode fechar @joaorobson
