### ISSUE TITLE
Fazer o MVP do servidor GO 

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.1-unbrake#89]
## Descrição

Desenvolver um sistema de Go que comunique com a placa via conexão serial e também forneça informações para o gráfico em tempo real do Front-end.

## Tarefas

- [ ] Escolher a forma de fornecer a informação em tempo real
- [ ] Integrar a solução acima no Go
- [ ] Integrar a solução acima no Front-End
- [ ] Decidir como vai ser feita a comunicação Go-API
- [ ] Escrever a API inicial de comunicação
- [ ] Escrever a abstração da comunicação serial

## Informação adicional

Boa sorte aos envolvidos

**Comment by Bumbleblo** [comment]
@joaorobson se quiser adicionar mais alguma coisa a esse épico fique a vontade
